# Monokai Themed Starship Prompt
"$schema" = 'https://starship.rs/config-schema.json'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold purple"

[git_status]
style = "bold red"
format = '[$all_status]($style) '

[nodejs]
symbol = "â¬¢ "
style = "bold green"
format = 'via [â¬¢ $version](bold green)'

[python]
symbol = "ğŸ "
style = "bold cyan"
format = 'via [ğŸ $version](bold cyan)'

[hostname]
disabled = true

[username]
disabled = true

[env_var]
symbol = "ğŸŒ "
style = "bold green"

[time]
format = "ğŸ•’ $time"


[conda]
format = '[$symbol$environment](dimmed green) '
symbol = "ğŸ…’ "
